# CloudFormation template format version, not the creation date
AWSTemplateFormatVersion: '2010-09-09'

# Template description
Description: Network Resources for cloudformation-iac-lab

# Define AWS resources to create
Resources:
  # Logical ID of the VPC within this template
  VPC:
    # Resource type: VPC
    Type: AWS::EC2::VPC
    Properties:
      # Private IPv4 address range for the VPC
      CidrBlock: '10.0.0.0/16'

      # Use default shared hardware tenancy for EC2 instances
      InstanceTenancy: default

      # Enable public DNS hostnames for eligible EC2 instances
      # This setting does not assign public IP addresses
      EnableDnsHostnames: true

      # Enable DNS resolution using the Amazon-provided DNS server
      EnableDnsSupport: true

      # Tags for resource identification and management
      Tags:
        # Resource name displayed in the AWS console
        - Key: Name
          Value: sample-vpc

        # Project name
        - Key: Project
          Value: cloudformation-iac-lab

        # Environment purpose
        - Key: Environment
          Value: learning

  # Public subnet in AZ in a.
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      # Reference the VPC defined in this template.
      VpcId: !Ref VPC
      CidrBlock: '10.0.0.0/20'
      AvailabilityZone: ap-northeast-1a

      # Automatically assign public IPv4 addresses to EC2 instances.
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: sample-subnet-public01
        - Key: Project
          Value: cloudformation-iac-lab
        - Key: Environment
          Value: learning
        - Key: Type
          Value: public

  # Public subnet in AZ c.
  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.16.0/20'
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: sample-subnet-public02
        - Key: Project
          Value: cloudformation-iac-lab
        - Key: Environment
          Value: learning
        - Key: Type
          Value: public

  # Private subnet in AZ a.
  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.64.0/20'
      AvailabilityZone: ap-northeast-1a

      # Do not automatically assign public IPv4 addresses.
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: sample-subnet-private01
        - Key: Project
          Value: cloudformation-iac-lab
        - Key: Environment
          Value: learning
        - Key: Type
          Value: private

  # Private subnet in AZ c.
  PrivateSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: '10.0.80.0/20'
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: sample-subnet-private02
        - Key: Project
          Value: cloudformation-iac-lab
        - Key: Environment
          Value: learning
        - Key: Type
          Value: private
    # Create an Internet Gateway.
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: sample-igw
        - Key: Project
          Value: cloudformation-iac-lab
        - Key: Environment
          Value: learning

  # Attach the Internet Gateway to the VPC.
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

# Values displayed in the stack Outputs tab
Outputs:
  # Output key
  VpcId:
    Description: Created VPC ID

    # Ref returns the ID of the VPC created by this template
    Value: !Ref VPC